import os
import json
import logging
from .config_manager import ConfigManager

logger = logging.getLogger(__name__)

class LanguageManager:
    DEFAULT_TRANSLATIONS = {
        'zh_CN': {
            '...': '[...]',
            'acrylic_tooltip': '启用后窗口背景将使用丙烯酸模糊效果',
            'actions': '操作',
            'active': '活跃',
            'adaptive_config': '自适应配置',
            'add_btn': '添加关键词',
            'add_new_volume': '增加新卷',
            'add_new_volume_btn': '增加新卷',
            'add_new_volume_btn2': '增加新卷',
            'add_rule': '添加规则',
            'add_volume_failed': '增加新卷失败',
            'all_members': '全部成员',
            'animations_tooltip': '启用后页面切换、悬浮弹跳、淡入等视觉动效将生效',
            'app_title': '小说助手',
            'area_scale': '面积缩放倍数',
            'auto_save_layout': '自动保存布局',
            'auto_save_layout_label': '自动保存布局',
            'auto_scan_label': '自动扫描',
            'avg_per_day': '日均',
            'base_font_size': '基础字号',
            'batch_create_label': '批量创建章节',
            'bg_color': '背景颜色',
            'bg_color_label': '背景色',
            'body_color': '正文字色',
            'body_font_size': '正文字号',
            'border_color': '边框颜色',
            'border_color_label': '边框色',
            'brightest_label': '最亮:',
            'brightness_range': '亮度区间:',
            'brightness_range_error': '亮度区间的最小值不能大于最大值！',
            'brightness_sort_tooltip': '启用后将按节点连接数从高到低排序节点亮度',
            'btn_bg': '按钮背景',
            'btn_bg_color_label': '按钮背景色',
            'btn_hover': '按钮悬停',
            'btn_hover_color_label': '按钮悬停色',
            'cancel': '取消',
            'cancel_rule': '取消',
            'cannot_determine_start_chapter': '无法确定开始章节',
            'card_font_size_label': '人物卡字号',
            'card_title_size_label': '人物卡标题字号',
            'chapter_1': '第一章',
            'chapter_creation': '章节创建',
            'chapter_preview_btn': '章节预览',
            'chapter_template_tool': '=== 章节模板创建工具 ===',
            'chapter_updated': '章节已更新',
            'check_directory_failed': '检查目录失败',
            'clear_file_failed': '清空文件失败',
            'col_mod_time': '修改时间',
            'col_title': '标题',
            'col_volume_chapter': '卷/章节',
            'col_word_count': '字数',
            'color_label': '颜色',
            'color_scheme_group': '色彩方案',
            'completed': '完成',
            'completed_cjk': '完成！CJK字符',
            'config_reloaded': '配置已重新加载！',
            'config_saved_applied': '配置已保存并应用！',
            'config_saved_restart': '配置已保存！\n重启程序后生效。',
            'confirm': '确认',
            'confirm_creation': '确认创建',
            'confirm_delete': '确认删除',
            'confirm_delete_rule': '确定要删除选中的规则吗？',
            'confirm_exit': '确认退出',
            'connect_button': '连接',
            'connection_range': '关联数区间:',
            'connection_threshold': '连接阈值',
            'connections_unit': ' 条',
            'continue_question': '是否继续？',
            'copy_first_10': '4. 复制前10章到 /novel/title/1',
            'create_chapter_btn': '创建章节',
            'create_chapter_failed': '创建章节失败',
            'create_chapters': '创建章节',
            'create_dir_failed': '创建目录失败',
            'create_env_failed': '创建运行环境失败',
            'create_folders': '1. 在当前目录创建 /all, /novel, /log 文件夹',
            'create_question': '是否创建？',
            'create_runtime_env': '创建运行环境',
            'create_sample_config': '创建示例配置',
            'create_title_folder': '3. 在 /novel 创建 title 文件夹',
            'created_successfully': '成功创建',
            'creating_runtime_env': '即将创建运行环境：',
            'creation_result': '创建结果',
            'daily_goal': '每日目标',
            'daily_target_words': '每日目标字数',
            'darkest_label': '最暗:',
            'default_text': '默认: ',
            'defined_rules': '已定义规则',
            'delete_btn': '删除关键词',
            'delete_empty_chapter_failed': '删除无内容章节失败',
            'delete_rule': '删除规则',
            'description_updated': '「{0}」的描述已更新',
            'deselect_all_btn': '取消全选',
            'detect_isolated_btn': '孤立检测',
            'dir_not_exist': '目录不存在',
            'dir_not_exist_err': '目录不存在',
            'dir_not_exist_question': '目录不存在：{0}\n是否创建？',
            'dir_not_writable': '目录不可写',
            'display_architecture_failed': '显示架构视图失败: {0}',
            'duplicate': '重复',
            'edge_width_label': '关系线宽',
            'edit_btn': '编辑关键词',
            'edit_queue': '待编辑队列',
            'empty_chapters_deleted': '删除无内容章节',
            'enable_acrylic': '开启丙烯酸效果',
            'enable_animations_label': '开启动效（页面切换/悬浮弹跳/淡入）',
            'enable_font_scaling_label': '开启字号自适应缩放',
            'enable_glow': '开启发光效果',
            'end_chapter_label': '结束章节',
            'end_must_gt_zero': '结束章节必须大于0',
            'enter_end_chapter': '输入结束章节号',
            'enter_file_suffix': '输入文件名后缀',
            'enter_start_chapter': '输入起始章节号',
            'enter_valid_int': '请输入有效的正整数',
            'env_init_tip': '请先点击「创建运行环境」按钮！',
            'env_not_initialized': '环境未初始化',
            'error': '错误',
            'error_color': '错误颜色',
            'error_color_label': '错误色',
            'execute_summary': '执行 Summary',
            'execution_result': '执行结果',
            'exit_confirm_message': '确定要退出吗？',
            'exit_confirm_msg': '确定要退出程序吗？\n所有线程将会安全停止。',
            'exit_program': '退出程序',
            'export_chapter_format': '章节标题格式',
            'export_failed': '导出失败',
            'export_failed_2': '导出失败:\n{0}',
            'export_filename_format': '文件名格式',
            'export_png_btn': '导出PNG',
            'export_report_btn': '导出报告',
            'export_success': '族谱图已导出到:\n{0}',
            'export_volume_format': '卷标题格式',
            'fg_color': '字体颜色',
            'fg_color_label': '前景/文字色',
            'file_suffix_label': '文件后缀:',
            'files_unit': '个文件',
            'filter_adventure': '事件',
            'filter_all': '全部',
            'filter_character': '人物',
            'filter_faction': '组织',
            'filter_foreshadowing': '伏笔',
            'filter_item': '物品',
            'filter_location': '地点',
            'filter_recent_15': '最近15条',
            'filter_recent_30': '最近30条',
            'filter_recent_50': '最近50条',
            'filter_relationship': '关系',
            'filter_skill': '技能',
            'filter_stopwords_label': '启用停用词过滤',
            'filter_time_point': '时间点',
            'focus_mode': '专注模式',
            'folder_exists': '文件夹 {0} 已存在！',
            'folder_status': '文件夹状态',
            'follow_theme': '跟随主题默认',
            'font_family_label': '字体名称',
            'font_increment': '字号增加量',
            'font_label': '字体',
            'font_scaling_label': '字号自适应缩放（可选）',
            'font_scaling_tooltip': '启用后根据窗口大小自适应调整字号大小',
            'font_size_label': '字号:',
            'format_config': '格式配置',
            'format_error_text': '格式错误',
            'format_help_chapter': '格式：{cn.up.Chapter}=第壹佰伍拾叁章、{cn.low.Chapter}=第一百五十三章、{cn.num.Chapter}=第153章、{en.Chapter}=Chapter153、{jp.Chapter}=第一百五十三章、{name}=后缀 | _在语言格式和{name}之间时自动转为·',
            'format_help_filename': '格式：{num}=数字、{cn.up.Chapter}=第壹佰伍拾叁章、{cn.low.Chapter}=第一百五十三章、{cn.num.Chapter}=第153章、{en.Chapter}=Chapter153、{jp.Chapter}=第一百五十三章、{title}=标题名、{types:xxx}=后缀 | 示例：{cn.low.Chapter}{title}{types:markdown} → 1第一章_title.md',
            'format_help_font_label': '格式帮助字号',
            'format_help_volume': '格式：{cn.up.Volume}=第壹佰伍拾叁卷、{cn.low.Volume}=第一百五十三卷、{cn.num.Volume}=第153卷、{en.Volume}=Volume153、{jp.Volume}=第一百五十三巻、{name}=卷名、{word_count}=字数 | _在语言格式和{name}之间时自动转为·',
            'freq_scan_failed': '词频扫描失败',
            'freq_track_group': '频度追踪',
            'generate_templates': '2. 在 /all 生成章节模板',
            'generating_chapters': '正在生成 {0} 章模板...',
            'glow_size_config': '发光大小配置',
            'glow_tooltip': '启用后节点将带有发光视觉效果',
            'graph_bg_color': '背景颜色',
            'graph_config': '图谱配置',
            'graph_font_size_label': '网络图字号',
            'grid_color_label': '网格颜色',
            'h1_color': '一级标题颜色',
            'h1_font_size': '一级标题字号',
            'h1_max_size_label': '一级标题最大字号',
            'h2_color': '二级标题颜色',
            'h2_font_size': '二级标题字号',
            'h2_max_size_label': '二级标题最大字号',
            'heartbeat_timeout_label': '心跳超时(秒)',
            'height_scale': '高度缩放倍数',
            'hint': '提示',
            'inactive_chapters_label': '暂隐阈值(章)',
            'init_and_create_tab': '初始化与创建章节',
            'init_folders_failed': '初始化文件夹失败',
            'init_novel_btn': '初始化小说目录',
            'initial_height': '初始高度',
            'initial_width': '初始宽度',
            'initialize_complete': '目录初始化完成！',
            'initialize_directory': '初始化目录',
            'initialize_directory_msg': '目录为空或没有找到卷文件夹，是否自动初始化？\n\n将创建：\n  - 1[new_0]/ 目录（第一卷）\n  - 10个无内容章节\n\n继续吗？',
            'initialize_failed': '初始化目录失败',
            'input_bg': '输入框背景',
            'input_bg_color': '输入框背景色',
            'input_error': '输入错误',
            'key': '[Key]',
            'keyword_color_label': '颜色:',
            'keyword_config': '关键词配置',
            'keyword_count': '关键词数量: {0}',
            'keyword_coverage': '关键词覆盖',
            'keyword_desc_label': '描述:',
            'keyword_list_title': '关键词列表',
            'keyword_manager': '关键词管理',
            'keyword_name_label': '关键词名:',
            'keyword_page_title': '=== 关键词管理系统 ===',
            'keyword_related_label': '相关关键词 (逗号分隔):',
            'keyword_tab_title': '关键词管理',
            'keyword_type_character': '人物',
            'keyword_type_custom': '自定义',
            'keyword_type_foreshadowing': '伏笔',
            'keyword_type_item': '物品',
            'keyword_type_label': '类型:',
            'keyword_type_location': '地点',
            'keyword_type_relationship': '关系',
            'keyword_type_skill': '技能',
            'keywords_only_label': '仅统计已有关键词',
            'kwlist_color_label': '关键词颜色',
            'kwlist_family_label': '关键词字体',
            'kwlist_font_size_label': '关键词字号',
            'kwlist_title_size_label': '关键词标题字号',
            'language': '语言',
            'language_changed_restart': '语言已更改，请重启程序以完全生效。',
            'language_config': '语言配置',
            'language_settings': '语言设置',
            'layout_ideal_distance': '布局理想距离',
            'layout_ideal_label': '布局理想长度',
            'legend_position': '图例位置',
            'legend_style': '图例样式',
            'legend_visible': '显示图例',
            'line_height_label': '行高',
            'link_bold': '链接加粗',
            'link_bold_label': '链接加粗',
            'link_color': '链接颜色',
            'link_font_size': '链接字号',
            'link_font_size_label': '链接字号',
            'link_italic': '链接斜体',
            'link_italic_label': '链接斜体',
            'log_auto_init_done': '已创建: 1[new_0]/ (10个空章节)',
            'log_auto_summary_err': '自动Summary失败: ',
            'log_auto_summary_merging': '新卷处理完成，自动运行Summary合并...',
            'log_complete_count': '完成! 共创建 {0} 个文件',
            'log_created_chapter': '创建: ',
            'log_export_failed': '导出失败',
            'log_exported_png': '已导出: ',
            'log_failed_chapter': '失败: ',
            'log_filter': '日志筛选',
            'log_font_size': '日志字号',
            'log_isolated_found': '发现 {0} 个孤立节点:',
            'log_layout_reset': '布局已重置，重新计算力导向位置',
            'log_layout_saved': '布局已保存',
            'log_new_vol_created': '创建新卷文件夹: {0}，监控启动后将自动处理标记',
            'log_new_vol_failed': '创建新卷失败: ',
            'log_no_isolated': '没有孤立节点，所有节点都有连线',
            'log_novel_dir_set': '小说目录已设置: ',
            'log_p2p_path': '路径: ',
            'log_path_not_found': '未找到 {0} 到 {1} 的路径',
            'log_rename_item': '重命名: {0} -> {1}',
            'log_summary_done': 'Summary合并完成',
            'log_wait_monitor': '等待监控线程结束...',
            'long_break': '长休息',
            'mark_new_volume_failed': '自动标记新卷失败',
            'mark_old_volume_failed': '自动标记旧卷失败',
            'max_nodes': '最大节点数',
            'max_size_label': '最大尺寸',
            'maximum': '最大:',
            'maximum_label': '最大值',
            'merge_selected_volumes': '合并选中卷',
            'merge_volumes_btn': '合并卷章',
            'min_height': '最小高度',
            'min_occurrences_label': '最少出现次数',
            'min_size_label': '最小尺寸',
            'min_width': '最小宽度',
            'min_word_length_label': '最小词长',
            'minimum': '最小:',
            'minimum_label': '最小值',
            'monitor_auto_process': '监控正在运行，将自动处理新卷。',
            'monitor_check_error': '监控检查异常',
            'monitor_config': '监控配置',
            'monitor_error': '监控线程错误',
            'monitor_fatal_error': '监控线程致命错误',
            'monitor_interval': '监控间隔',
            'monitor_management': '监控管理',
            'monitor_started': '监控已启动',
            'monitor_stopped': '监控已停止',
            'monitor_system': '=== 监控管理系统 ===',
            'neural_graph_group': '神经网络图',
            'new': '新增',
            'new_chapter_detected': '检测到新章节',
            'new_chapters_added': '新增章节',
            'new_folder_detected': '发现新文件夹',
            'new_folder_state': '发现新文件夹状态',
            'new_volume_created': '已创建新卷',
            'new_volume_marked': '自动标记新卷',
            'no_data_to_export': '暂无数据可导出，请先刷新',
            'no_templates_available': '无可用模板',
            'no_vol_folders_warn': '未找到卷文件夹',
            'no_volume_folders': '没有找到卷文件夹！',
            'node_already_exists': '节点已存在',
            'node_brightness_range': '节点亮度范围',
            'node_limit_label': '节点上限',
            'node_size_range': '节点大小范围',
            'node_visual_effects': '节点视觉效果',
            'non_whitespace': '非空白字符',
            'novel_dir': '小说目录:',
            'novel_dir_label': '小说目录',
            'novel_dir_not_set': '请先设置小说目录',
            'novel_info': '小说信息',
            'ok': 'OK',
            'old_volume_marked': '自动标记旧卷',
            'param_config_page': '=== 参数配置 ===',
            'parameter_config': '参数配置',
            'pause': '暂停',
            'please_init_or_select_novel_dir': '请先初始化或选择小说目录',
            'please_select_at_least_one_volume': '请至少选择一个卷',
            'pos_bottom_left': '左下角',
            'pos_bottom_right': '右下角',
            'pos_top_left': '左上角',
            'pos_top_right': '右上角',
            'pregenerate_chapters': '预生成章节数',
            'prev_volume_not_found': '未找到上一卷',
            'preview_color': '预览颜色',
            'preview_font_size': '预览字号',
            'preview_text': '预览: ',
            'process_new_volume_failed': '处理新卷文件夹失败',
            'progress': '进度',
            'prompt': '提示',
            'quick_operations': '快速操作',
            'range_min_max_error': '关联数区间的最小值不能大于最大值！',
            'range_rule_conflict_error': '范围规则不能与阈值规则共存！',
            'read_failed': '读取失败',
            'recent_operations': '最近操作',
            'reference_width': '参考宽度',
            'refresh_btn': '刷新关键词',
            'refresh_all_btn': '刷新全部',
            'reload': '重新加载',
            'reload_config': '重载配置',
            'reload_failed': '重新加载配置失败',
            'reset': '重置',
            'reset_config_confirm': '确定要重置所有配置为默认值吗？',
            'reset_config_done': '配置已重置为默认值',
            'reset_default_btn': '恢复默认',
            'reset_layout_btn': '重置布局',
            'restart_to_apply': '请重启程序以使语言更改生效。',
            'resume': '继续',
            'rule_conflict': '规则冲突',
            'rule_type': '规则类型',
            'rules_help': '规则的连接数阈值 - 当节点连接数达到此值时应用对应大小和亮度。范围规则作用于一个连接数区间。',
            'run_mode': '运行模式',
            'sample_config_created': '示例配置已创建: {0}',
            'save_and_apply': '保存并应用',
            'save_and_exit_btn': '保存并退出',
            'save_apply_failed': '保存并应用失败',
            'save_config': '保存配置',
            'save_config_failed': '保存配置失败',
            'save_directory_label': '保存目录:',
            'save_layout_btn': '保存布局',
            'save_rule': '保存规则',
            'save_rule_failed': '保存规则失败',
            'saving_text': '保存中...',
            'scaling_range': '缩放范围',
            'scan_failed': '词频扫描失败:\n{0}',
            'scan_in_progress': '词频扫描正在进行中，请稍候',
            'search_placeholder': '搜索节点... (Enter 定位)',
            'select': '选择...',
            'select_all_btn': '全选',
            'select_at_least_one_volume': '请至少选择一个卷',
            'select_directory': '选择目录',
            'select_language': '选择语言',
            'select_novel_directory': '选择小说目录',
            'select_root_node_first': '请先选择根节点并生成族谱图',
            'select_rule_first': '请先选择要删除的规则',
            'select_volumes_label': '选择要合并的卷：',
            'set_novel_dir_first': '请先设置小说目录',
            'short_break': '短休息',
            'show': '显示',
            'size_label': '大小',
            'size_range': '大小范围',
            'size_sort_tooltip': '启用后将按节点连接数从高到低排序节点大小',
            'skip_break': '跳过休息',
            'skipped_existing': '跳过已存在的',
            'sort_by_connection_brightness': '按连接数排序节点亮度',
            'sort_by_connection_size': '按连接数排序节点大小',
            'stale_gap_label': '最后N章未出现判stale',
            'stale_ratio_label': '临时称谓检测比例',
            'start': '开始',
            'start_chapter_label': '起始章节',
            'start_creation': '开始创建',
            'start_gt_end_error': '起始章节不能大于结束章节',
            'start_lt_end': '起始章节不能大于结束章节',
            'start_monitor': '启动监控',
            'start_monitor_process': '请启动监控来处理新卷。',
            'start_must_gt_zero': '起始章节必须大于0',
            'start_new_program': '启动新程序',
            'start_program_failed': '启动新程序失败',
            'start_program_now_question': '是否立即启动新程序？',
            'statistics': '统计',
            'stats_and_rename': '2. 统计并重命名文件夹（默认）',
            'stats_only': '1. 仅统计并收集（不重命名文件夹）',
            'status_running': '状态: 运行中',
            'status_stopped': '状态: 已停止',
            'stop_monitor': '停止监控',
            'structure_preview': '架构预览',
            'success': '成功',
            'summary_execute_failed': 'Summary执行失败',
            'summary_merge_tool': '卷与章合并',
            'summary_triggered': '触发Summary',
            'tab_config': '标签页配置',
            'target': '目标',
            'template_saved': '模板已保存',
            'theme_label': '主题',
            'theme_tooltip': '选择应用程序的视觉主题',
            'threshold_exists_error': '阈值 {0} 已存在，区间规则不能与阈值规则共存！',
            'threshold_label': '阈值',
            'tip_change_language': '提示：切换语言后点击「保存并应用」生效',
            'title_font_size': '标题字号',
            'today': '今日',
            'total_words': '总字数',
            'trigger_word_count': '触发字数',
            'ui_color_config': 'UI 颜色配置',
            'ui_size_config': 'UI 尺寸配置',
            'user_guide': '使用说明',
            'user_guide_page': '=== 使用说明 ===',
            'view_all_keywords': '全部关键词',
            'view_by_type': '按类型查看',
            'view_card': '人物卡',
            'view_frequency': '频度仪表盘',
            'view_list': '列表视图',
            'view_neural': '神经网络图',
            'volume_details': '各卷详情',
            'volume_folder_format': '卷文件夹格式',
            'volume_merge_title': '卷与章合并',
            'volume_target_words': '卷目标字数',
            'volume_word_count': '本卷字数',
            'waiting_for_write': '等待写入',
            'warn_color_label': '警告色',
            'warning': '警告',
            'word_unit': ' 字',
            'writing_days': '写作天数',
            'writing_goal_config': '写作目标配置',
            'writing_stats': '写作统计',
            'writing_timer': '写作计时器',
            'writing_trend': '写作趋势',
            '{k}': '[{K}]',
            'help_content': {
            },
        },
        'en_US': {
            '...': '...',
            'acrylic_tooltip': 'Window background will use acrylic blur effect when enabled',
            'actions': 'Actions',
            'active': 'Active',
            'adaptive_config': 'Adaptive Configuration',
            'add_btn': 'Add Keyword',
            'add_new_volume': 'Add New Volume',
            'add_new_volume_btn': 'Add New Volume',
            'add_new_volume_btn2': 'Add New Volume',
            'add_rule': 'Add Rule',
            'add_volume_failed': 'Add new volume failed',
            'all_members': 'All Members',
            'animations_tooltip': 'Enable visual effects for page switching, hover bounce, and fade-in animations',
            'app_title': 'Novel Helper',
            'area_scale': 'Area Scale Factor',
            'auto_save_layout': 'Auto Save Layout',
            'auto_save_layout_label': 'Auto Save Layout',
            'auto_scan_label': 'Auto Scan',
            'avg_per_day': 'Avg/Day',
            'base_font_size': 'Base Font Size',
            'batch_create_label': 'Batch Create',
            'bg_color': 'Background Color',
            'bg_color_label': 'Background',
            'body_color': 'Body Color',
            'body_font_size': 'Body Font Size',
            'border_color': 'Border Color',
            'border_color_label': 'Border',
            'brightest_label': 'Brightest:',
            'brightness_range': 'Brightness Range:',
            'brightness_range_error': 'Min brightness cannot be greater than max brightness!',
            'brightness_sort_tooltip': 'Sort node brightness by connection count from high to low',
            'btn_bg': 'Button Background',
            'btn_bg_color_label': 'Button BG Color',
            'btn_hover': 'Button Hover',
            'btn_hover_color_label': 'Button Hover Color',
            'cancel': 'Cancel',
            'cancel_rule': 'Cancel',
            'cannot_determine_start_chapter': 'Cannot determine start chapter',
            'card_font_size_label': 'Card Font Size',
            'card_title_size_label': 'Card Title Size',
            'chapter_1': 'Chapter 1',
            'chapter_creation': 'Chapter Creation',
            'chapter_preview_btn': 'Chapter Preview',
            'chapter_template_tool': '=== Chapter Template Creation Tool ===',
            'chapter_updated': 'Chapter Updated',
            'check_directory_failed': 'Check directory failed',
            'clear_file_failed': 'Clear file failed',
            'col_mod_time': 'Modified',
            'col_title': 'Title',
            'col_volume_chapter': 'Vol/Chapter',
            'col_word_count': 'Words',
            'color_label': 'Color',
            'color_scheme_group': 'Color Scheme',
            'completed': 'Completed',
            'completed_cjk': 'Completed! CJK characters',
            'config_reloaded': 'Configuration reloaded!',
            'config_saved_applied': 'Configuration saved and applied!',
            'config_saved_restart': 'Configuration saved! Restart to take effect.',
            'confirm': 'Confirm',
            'confirm_creation': 'Confirm Creation',
            'confirm_delete': 'Confirm Delete',
            'confirm_delete_rule': 'Are you sure you want to delete the selected rule?',
            'confirm_exit': 'Confirm Exit',
            'connect_button': 'Connect',
            'connection_range': 'Connection Range:',
            'connection_threshold': 'Connection Threshold',
            'connections_unit': ' connections',
            'continue_question': 'Continue?',
            'copy_first_10': '4. Copy first 10 chapters to /novel/title/1',
            'create_chapter_btn': 'Create Chapter',
            'create_chapter_failed': 'Create chapter failed',
            'create_chapters': 'Create Chapters',
            'create_dir_failed': 'Create directory failed',
            'create_env_failed': 'Failed to create runtime environment',
            'create_folders': '1. Create /all, /novel, /log folders in current directory',
            'create_question': 'Create?',
            'create_runtime_env': 'Create Runtime Environment',
            'create_sample_config': 'Create Sample Config',
            'create_title_folder': '3. Create title folder in /novel',
            'created_successfully': 'Successfully created',
            'creating_runtime_env': 'Creating runtime environment:',
            'creation_result': 'Creation Result',
            'daily_goal': 'Daily Goal',
            'daily_target_words': 'Daily Target Words',
            'darkest_label': 'Darkest:',
            'default_text': 'Default: ',
            'defined_rules': 'Defined Rules',
            'delete_btn': 'Delete Keyword',
            'delete_empty_chapter_failed': 'Delete empty chapter failed',
            'delete_rule': 'Delete Rule',
            'description_updated': 'Description for \'{0}\' has been updated',
            'deselect_all_btn': 'Deselect All',
            'detect_isolated_btn': 'Detect Isolated',
            'dir_not_exist': 'Directory does not exist',
            'dir_not_exist_err': 'Dir not exist',
            'dir_not_exist_question': 'Directory does not exist: {0}\nCreate it?',
            'dir_not_writable': 'Directory not writable',
            'display_architecture_failed': 'Failed to display architecture view: {0}',
            'duplicate': 'Duplicate',
            'edge_width_label': 'Edge Width',
            'edit_btn': 'Edit Keyword',
            'edit_queue': 'Edit Queue',
            'empty_chapters_deleted': 'Empty Chapters Deleted',
            'enable_acrylic': 'Enable Acrylic Effect',
            'enable_animations_label': 'Enable Animations (Page Switch/Hover/Fade)',
            'enable_font_scaling_label': 'Enable Font Auto-scaling',
            'enable_glow': 'Enable Glow Effect',
            'end_chapter_label': 'End Chapter',
            'end_must_gt_zero': 'End chapter must be greater than 0',
            'enter_end_chapter': 'Enter End Chapter',
            'enter_file_suffix': 'Enter File Name Suffix',
            'enter_start_chapter': 'Enter Start Chapter',
            'enter_valid_int': 'Please enter a valid positive integer',
            'env_init_tip': 'Please click Create Runtime Environment first!',
            'env_not_initialized': 'Environment Not Initialized',
            'error': 'Error',
            'error_color': 'Error Color',
            'error_color_label': 'Error Color',
            'execute_summary': 'Execute Summary',
            'execution_result': 'Execution Result',
            'exit_confirm_message': 'Are you sure you want to exit?',
            'exit_confirm_msg': 'Are you sure to exit? All threads will stop safely.',
            'exit_program': 'Exit Program',
            'export_chapter_format': 'Chapter Title Format',
            'export_failed': 'Export failed',
            'export_failed_2': 'Export failed:\n{0}',
            'export_filename_format': 'Filename Format',
            'export_png_btn': 'Export PNG',
            'export_report_btn': 'Export Report',
            'export_success': 'Genealogy tree exported to:\n{0}',
            'export_volume_format': 'Volume Title Format',
            'fg_color': 'Font Color',
            'fg_color_label': 'Foreground',
            'file_suffix_label': 'File Suffix:',
            'files_unit': 'files',
            'filter_adventure': 'Event',
            'filter_all': 'All',
            'filter_character': 'Character',
            'filter_faction': 'Faction',
            'filter_foreshadowing': 'Foreshadowing',
            'filter_item': 'Item',
            'filter_location': 'Location',
            'filter_recent_15': 'Recent 15',
            'filter_recent_30': 'Recent 30',
            'filter_recent_50': 'Recent 50',
            'filter_relationship': 'Relationship',
            'filter_skill': 'Skill',
            'filter_stopwords_label': 'Enable Stopwords Filter',
            'filter_time_point': 'Time Point',
            'focus_mode': 'Focus Mode',
            'folder_exists': 'Folder {0} already exists!',
            'folder_status': 'Folder Status',
            'follow_theme': 'Follow Theme Default',
            'font_family_label': 'Font Family',
            'font_increment': 'Font Size Increment',
            'font_label': 'Font',
            'font_scaling_label': 'Font Auto-scaling (Optional)',
            'font_scaling_tooltip': 'Automatically adjust font size based on window size',
            'font_size_label': 'Font Size:',
            'format_config': 'Format Configuration',
            'format_error_text': 'Format Error',
            'format_help_chapter': 'Format: {cn.up.Chapter}=第壹佰伍拾叁章, {cn.low.Chapter}=第一百五十三章, {cn.num.Chapter}=第153章, {en.Chapter}=Chapter153, {jp.Chapter}=第一百五十三章, {name}=suffix | _ between lang format and {name} auto to ·',
            'format_help_filename': 'Format: {num}=num, {cn.up.Chapter}=第壹佰伍拾叁章, {cn.low.Chapter}=第一百五十三章, {cn.num.Chapter}=第153章, {en.Chapter}=Chapter153, {jp.Chapter}=第一百五十三章, {title}=title, {types:xxx}=extension | Example: {cn.low.Chapter}{title}{types:markdown} → 1第一章_title.md',
            'format_help_font_label': 'Help Font Size',
            'format_help_volume': 'Format: {cn.up.Volume}=第壹佰伍拾叁卷, {cn.low.Volume}=第一百五十三卷, {cn.num.Volume}=第153卷, {en.Volume}=Volume153, {jp.Volume}=第一百五十三巻, {name}=name, {word_count}=count | _ between lang format and {name} auto to ·',
            'freq_scan_failed': 'Frequency Scan Failed',
            'freq_track_group': 'Frequency Tracking',
            'generate_templates': '2. Generate chapter templates in /all',
            'generating_chapters': 'Generating {0} chapter templates...',
            'glow_size_config': 'Glow Size Config',
            'glow_tooltip': 'Nodes will have a visual glow effect when enabled',
            'graph_bg_color': 'Background Color',
            'graph_config': 'Graph Config',
            'graph_font_size_label': 'Graph Font Size',
            'grid_color_label': 'Grid Color',
            'h1_color': 'H1 Color',
            'h1_font_size': 'H1 Font Size',
            'h2_color': 'H2 Color',
            'h2_font_size': 'H2 Font Size',
            'heartbeat_timeout_label': 'Heartbeat Timeout(s)',
            'height_scale': 'Height Scale Factor',
            'hint': 'Hint',
            'inactive_chapters_label': 'Inactive Ch.(ch)',
            'init_and_create_tab': 'Init && Create',
            'init_folders_failed': 'Initialize folders failed',
            'init_novel_btn': 'Initialize Novel',
            'initial_height': 'Initial Height',
            'initial_width': 'Initial Width',
            'initialize_complete': 'Directory initialization complete!',
            'initialize_directory': 'Initialize Directory',
            'initialize_directory_msg': 'Directory is empty or no volume folders found. Auto-initialize?\n\nWill create:\n  - 1[new_0]/ (Volume 1)\n  - 10 empty chapters\n\nContinue?',
            'initialize_failed': 'Initialize directory failed',
            'input_bg': 'Input Background',
            'input_bg_color': 'Input BG Color',
            'input_error': 'Input Error',
            'key': 'Key',
            'keyword_color_label': 'Color:',
            'keyword_config': 'Keyword Config',
            'keyword_count': 'Keyword Count: {0}',
            'keyword_coverage': 'Keyword Coverage',
            'keyword_desc_label': 'Description:',
            'keyword_list_title': 'Keyword List',
            'keyword_manager': 'Keyword Manager',
            'keyword_name_label': 'Keyword Name:',
            'keyword_page_title': '=== Keyword Management System ===',
            'keyword_related_label': 'Related Keywords (comma sep):',
            'keyword_tab_title': 'Keyword Manager',
            'keyword_type_character': 'Character',
            'keyword_type_custom': 'Custom',
            'keyword_type_foreshadowing': 'Foreshadowing',
            'keyword_type_item': 'Item',
            'keyword_type_label': 'Type:',
            'keyword_type_location': 'Location',
            'keyword_type_relationship': 'Relationship',
            'keyword_type_skill': 'Skill',
            'keywords_only_label': 'Keywords Only',
            'kwlist_color_label': 'Keyword Color',
            'kwlist_family_label': 'Keyword Font',
            'kwlist_font_size_label': 'Keyword Font Size',
            'kwlist_title_size_label': 'Keyword Title Size',
            'language': 'Language',
            'language_changed_restart': 'Language changed. Please restart the program for full effect.',
            'language_config': 'Language Configuration',
            'language_settings': 'Language Settings',
            'layout_ideal_distance': 'Ideal Layout Distance',
            'layout_ideal_label': 'Ideal Length',
            'legend_position': 'Legend Position',
            'legend_style': 'Legend Style',
            'legend_visible': 'Show Legend',
            'line_height_label': 'Line Height',
            'link_bold': 'Link Bold',
            'link_color': 'Link Color',
            'link_font_size': 'Link Font Size',
            'link_italic': 'Link Italic',
            'log_auto_init_done': 'Created: 1[new_0]/ (10 empty)',
            'log_auto_summary_err': 'Auto Summary failed: ',
            'log_auto_summary_merging': 'New vol processed, running Summary...',
            'log_complete_count': 'Done! {0} files created',
            'log_created_chapter': 'Created: ',
            'log_export_failed': 'Export failed',
            'log_exported_png': 'Exported: ',
            'log_failed_chapter': 'Failed: ',
            'log_filter': 'Log Filter',
            'log_font_size': 'Log Font Size',
            'log_isolated_found': 'Found {0} isolated nodes:',
            'log_layout_reset': 'Layout reset, recalculating',
            'log_layout_saved': 'Layout saved',
            'log_new_vol_created': 'New vol folder: {0}, monitor will process',
            'log_new_vol_failed': 'Create vol failed: ',
            'log_no_isolated': 'No isolated nodes',
            'log_novel_dir_set': 'Novel dir set: ',
            'log_p2p_path': 'Path: ',
            'log_path_not_found': 'No path {0}->{1}',
            'log_rename_item': 'Rename: {0} -> {1}',
            'log_summary_done': 'Summary merge done',
            'log_wait_monitor': 'Waiting for monitor...',
            'long_break': 'Long Break',
            'mark_new_volume_failed': 'Mark new volume failed',
            'mark_old_volume_failed': 'Mark old volume failed',
            'max_nodes': 'Max Nodes',
            'max_size_label': 'Max Size',
            'maximum': 'Max:',
            'maximum_label': 'Maximum',
            'merge_selected_volumes': 'Merge Selected',
            'merge_volumes_btn': 'Merge Volumes',
            'min_height': 'Minimum Height',
            'min_occurrences_label': 'Min Occurrences',
            'min_size_label': 'Min Size',
            'min_width': 'Minimum Width',
            'min_word_length_label': 'Min Word Length',
            'minimum': 'Min:',
            'minimum_label': 'Minimum',
            'monitor_auto_process': 'Monitor is running, will process automatically.',
            'monitor_check_error': 'Monitor check error',
            'monitor_config': 'Monitor Configuration',
            'monitor_error': 'Monitor thread error',
            'monitor_fatal_error': 'Monitor thread fatal error',
            'monitor_interval': 'Monitor Interval',
            'monitor_management': 'Monitor Management',
            'monitor_started': 'Monitor Started',
            'monitor_stopped': 'Monitor Stopped',
            'monitor_system': '=== Monitor Management System ===',
            'neural_graph_group': 'Neural Graph',
            'new': 'New',
            'new_chapter_detected': 'New Chapter Detected',
            'new_chapters_added': 'New Chapters Added',
            'new_folder_detected': 'New Folder Detected',
            'new_folder_state': 'New folder state found',
            'new_volume_created': 'New volume created',
            'new_volume_marked': 'New Volume Marked',
            'no_data_to_export': 'No data to export, please refresh first',
            'no_templates_available': 'No Templates Available',
            'no_vol_folders_warn': 'No volume folders',
            'no_volume_folders': 'No volume folders found!',
            'node_already_exists': 'Node already exists',
            'node_brightness_range': 'Node Brightness Range',
            'node_limit_label': 'Node Limit',
            'node_size_range': 'Node Size Range',
            'node_visual_effects': 'Node Visual Effects',
            'non_whitespace': 'Non-whitespace characters',
            'novel_dir': 'Novel Directory:',
            'novel_dir_label': 'Novel Directory',
            'novel_dir_not_set': 'Set novel directory first',
            'novel_info': 'Novel Info',
            'ok': 'OK',
            'old_volume_marked': 'Old Volume Marked',
            'param_config_page': '=== Parameter Configuration ===',
            'parameter_config': 'Parameter Configuration',
            'pause': 'Pause',
            'please_init_or_select_novel_dir': 'Please initialize or select a novel directory first',
            'please_select_at_least_one_volume': 'Please select at least one volume',
            'pos_bottom_left': 'Bottom Left',
            'pos_bottom_right': 'Bottom Right',
            'pos_top_left': 'Top Left',
            'pos_top_right': 'Top Right',
            'pregenerate_chapters': 'Pre-generate Chapters',
            'prev_volume_not_found': 'Previous volume not found',
            'preview_color': 'Preview Color',
            'preview_font_size': 'Preview Font Size',
            'preview_text': 'Preview: ',
            'process_new_volume_failed': 'Process new volume folder failed',
            'progress': 'Progress',
            'prompt': 'Prompt',
            'quick_operations': 'Quick Operations',
            'range_min_max_error': 'Min value cannot be greater than max value!',
            'range_rule_conflict_error': 'Range rules cannot coexist with threshold rules!',
            'read_failed': 'Read failed',
            'recent_operations': 'Recent Operations',
            'reference_width': 'Reference Width',
            'refresh_btn': 'Refresh Keywords',
            'refresh_all_btn': 'Refresh All',
            'reload': 'Reload',
            'reload_config': 'Reload Config',
            'reload_failed': 'Reload configuration failed',
            'reset': 'Reset',
            'reset_config_confirm': 'Are you sure you want to reset all settings to defaults?',
            'reset_config_done': 'Settings have been reset to defaults',
            'reset_default_btn': 'Reset Default',
            'reset_layout_btn': 'Reset Layout',
            'restart_to_apply': 'Please restart the program to apply the language change.',
            'resume': 'Resume',
            'rule_conflict': 'Rule Conflict',
            'rule_type': 'Rule Type',
            'rules_help': 'Connection count threshold - when node connections reach this value, the corresponding size and brightness are applied. Range rules work on a connection interval.',
            'run_mode': 'Run Mode',
            'sample_config_created': 'Sample config created: {0}',
            'save_and_apply': 'Save & Apply',
            'save_and_exit_btn': 'Save && Exit',
            'save_apply_failed': 'Save and apply failed',
            'save_config': 'Save Configuration',
            'save_config_failed': 'Save configuration failed',
            'save_directory_label': 'Save Directory:',
            'save_layout_btn': 'Save Layout',
            'save_rule': 'Save Rule',
            'save_rule_failed': 'Failed to save rule',
            'saving_text': 'Saving...',
            'scaling_range': 'Scaling Range',
            'scan_failed': 'Frequency scan failed:\n{0}',
            'scan_in_progress': 'Frequency scan in progress, please wait',
            'search_placeholder': 'Search nodes... (Enter)',
            'select': 'Select...',
            'select_all_btn': 'Select All',
            'select_at_least_one_volume': 'Please select at least one volume',
            'select_directory': 'Select Directory',
            'select_language': 'Select Language',
            'select_novel_directory': 'Select Novel Directory',
            'select_root_node_first': 'Please select a root node and generate the genealogy tree first',
            'select_rule_first': 'Please select a rule to delete first',
            'select_volumes_label': 'Select volumes to merge:',
            'set_novel_dir_first': 'Please set the novel directory first',
            'short_break': 'Short Break',
            'show': 'Show',
            'size_label': 'Size',
            'size_range': 'Size Range',
            'size_sort_tooltip': 'Sort node sizes by connection count from high to low',
            'skip_break': 'Skip Break',
            'skipped_existing': 'Skipped existing',
            'sort_by_connection_brightness': 'Sort Node Brightness by Connection Count',
            'sort_by_connection_size': 'Sort Nodes by Connection Count',
            'stale_gap_label': 'Stale Gap Chapters',
            'stale_ratio_label': 'Stale Detection Ratio',
            'start': 'Start',
            'start_chapter_label': 'Start Chapter',
            'start_creation': 'Start Creation',
            'start_gt_end_error': 'Start > End',
            'start_lt_end': 'Start cannot be greater than end',
            'start_monitor': 'Start Monitor',
            'start_monitor_process': 'Please start monitor to process new volume.',
            'start_must_gt_zero': 'Start chapter must be greater than 0',
            'start_new_program': 'Start New Program',
            'start_program_failed': 'Failed to start new program',
            'start_program_now_question': 'Start the new program now?',
            'statistics': 'Statistics',
            'stats_and_rename': '2. Statistics And Rename',
            'stats_only': '1. Statistics Only (No Rename)',
            'status_running': 'Status: Running',
            'status_stopped': 'Status: Stopped',
            'stop_monitor': 'Stop Monitor',
            'structure_preview': 'Structure Preview',
            'success': 'Success',
            'summary_execute_failed': 'Summary execution failed',
            'summary_merge_tool': 'Volume & Chapter Merge',
            'summary_triggered': 'Summary Triggered',
            'tab_config': 'Tab Config',
            'target': 'Target',
            'template_saved': 'Template saved',
            'theme_label': 'Theme',
            'theme_tooltip': 'Select the visual theme for the application',
            'threshold_exists_error': 'Threshold {0} already exists. Range rules cannot coexist with threshold rules!',
            'threshold_label': 'Threshold',
            'tip_change_language': 'Tip: Click Save & Apply after changing language',
            'title_font_size': 'Title Font Size',
            'today': 'Today',
            'total_words': 'Total Words',
            'trigger_word_count': 'Trigger Word Count',
            'ui_color_config': 'UI Color Configuration',
            'ui_size_config': 'UI Size Configuration',
            'user_guide': 'User Guide',
            'user_guide_page': '=== User Guide ===',
            'view_all_keywords': 'All Keywords',
            'view_by_type': 'View By Type',
            'view_card': 'Card View',
            'view_frequency': 'Frequency Dashboard',
            'view_list': 'List View',
            'view_neural': 'Neural Graph',
            'volume_details': 'Volume Details',
            'volume_folder_format': 'Volume Folder Format',
            'volume_merge_title': 'Volume & Chapter Merge',
            'volume_target_words': 'Volume Target Words',
            'volume_word_count': 'Volume Word Count',
            'waiting_for_write': 'Waiting for Write',
            'warn_color_label': 'Warning Color',
            'warning': 'Warning',
            'word_unit': ' words',
            'writing_days': 'Writing Days',
            'writing_goal_config': 'Writing Goal Config',
            'writing_stats': 'Writing Stats',
            'writing_timer': 'Writing Timer',
            'writing_trend': 'Writing Trend',
            '{k}': '{K}',
        },
        'ja_JP': {
            '...': '...',
            'acrylic_tooltip': '有効にするとウィンドウ背景にアクリルぼかし効果が適用されます',
            'actions': '操作',
            'active': 'アクティブ',
            'adaptive_config': '適応設定',
            'add_btn': 'キーワード追加',
            'add_new_volume': '新規巻追加',
            'add_new_volume_btn': '新規巻追加',
            'add_new_volume_btn2': '新規追加',
            'add_rule': 'ルール追加',
            'add_volume_failed': '新規巻の追加に失敗しました',
            'all_members': '全メンバー',
            'animations_tooltip': 'ページ切替、ホバーバウンス、フェードインなどの視覚効果を有効にします',
            'app_title': '小説ヘルパー',
            'area_scale': '面積倍率',
            'auto_save_layout': 'レイアウト自動保存',
            'auto_save_layout_label': '自動保存',
            'auto_scan_label': '自動スキャン',
            'avg_per_day': '1日平均',
            'base_font_size': '基本フォントサイズ',
            'batch_create_label': '一括作成',
            'bg_color': '背景色',
            'bg_color_label': '背景色',
            'body_color': '本文色',
            'body_font_size': '本文フォントサイズ',
            'border_color': 'ボーダー色',
            'border_color_label': '枠色',
            'brightest_label': '最明:',
            'brightness_range': '輝度範囲:',
            'brightness_range_error': '最小輝度は最大輝度より大きくできません！',
            'brightness_sort_tooltip': '接続数の多い順にノードの明るさを並べ替えます',
            'btn_bg': 'ボタンバックグラウンド',
            'btn_bg_color_label': 'ボタン背景色',
            'btn_hover': 'ボタンホバー',
            'btn_hover_color_label': 'ボタンホバー色',
            'cancel': 'キャンセル',
            'cancel_rule': 'キャンセル',
            'cannot_determine_start_chapter': '開始章を特定できません',
            'card_font_size_label': 'カード字号',
            'card_title_size_label': 'カードタイトル字号',
            'chapter_1': '第1章',
            'chapter_creation': '章作成',
            'chapter_preview_btn': '章プレビュー',
            'chapter_template_tool': '=== 章テンプレート作成ツール ===',
            'chapter_updated': '章更新',
            'check_directory_failed': 'ディレクトリのチェックに失敗しました',
            'clear_file_failed': 'ファイルのクリアに失敗しました',
            'col_mod_time': '更新時間',
            'col_title': 'タイトル',
            'col_volume_chapter': '巻/章',
            'col_word_count': '字数',
            'color_label': '色',
            'color_scheme_group': '色彩設定',
            'completed': '完了',
            'completed_cjk': '完成！CJK文字',
            'config_reloaded': '設定が再読み込みされました！',
            'config_saved_applied': '設定が保存され適用されました！',
            'config_saved_restart': '設定が保存されました！再起動後に有効になります。',
            'confirm': '確認',
            'confirm_creation': '作成確認',
            'confirm_delete': '削除確認',
            'confirm_delete_rule': '選択したルールを削除してもよろしいですか？',
            'confirm_exit': '終了確認',
            'connect_button': '接続',
            'connection_range': '関連数範囲:',
            'connection_threshold': '接続しきい値',
            'connections_unit': ' 接続',
            'continue_question': '続行しますか？',
            'copy_first_10': '4. 最初の10章を /novel/title/1 にコピー',
            'create_chapter_btn': '章を作成',
            'create_chapter_failed': '章の作成に失敗',
            'create_chapters': 'チャプター作成',
            'create_dir_failed': 'ディレクトリの作成に失敗しました',
            'create_env_failed': '実行環境作成に失敗しました',
            'create_folders': '1. 現在のディレクトリに /all, /novel, /log フォルダを作成',
            'create_question': '作成しますか？',
            'create_runtime_env': '実行環境作成',
            'create_sample_config': 'サンプル設定作成',
            'create_title_folder': '3. /novel に title フォルダを作成',
            'created_successfully': '作成成功',
            'creating_runtime_env': '実行環境を作成中：',
            'creation_result': '作成結果',
            'daily_goal': '1日目標',
            'daily_target_words': '1日目標文字数',
            'darkest_label': '最暗:',
            'default_text': 'デフォルト: ',
            'defined_rules': '定義済みルール',
            'delete_btn': 'キーワード削除',
            'delete_empty_chapter_failed': '空章の削除に失敗',
            'delete_rule': 'ルール削除',
            'description_updated': '「{0}」の説明が更新されました',
            'deselect_all_btn': '全解除',
            'detect_isolated_btn': '孤立検出',
            'dir_not_exist': 'ディレクトリが存在しません',
            'dir_not_exist_err': 'ディレクトリなし',
            'dir_not_exist_question': 'ディレクトリが存在しません: {0}\n作成しますか？',
            'dir_not_writable': 'ディレクトリは書き込めません',
            'display_architecture_failed': 'アーキテクチャビューの表示に失敗: {0}',
            'duplicate': '重複',
            'edge_width_label': 'エッジ幅',
            'edit_btn': 'キーワード編集',
            'edit_queue': '編集キュー',
            'empty_chapters_deleted': '空章削除',
            'enable_acrylic': 'アクリル効果を有効化',
            'enable_animations_label': 'アニメーション有効化（切替/ホバー/フェード）',
            'enable_font_scaling_label': 'フォント自動スケーリングを有効化',
            'enable_glow': 'グロー効果を有効化',
            'end_chapter_label': '終了章',
            'end_must_gt_zero': '終了章は0より大きくなければなりません',
            'enter_end_chapter': '終了章を入力',
            'enter_file_suffix': 'ファイル名接尾辞を入力',
            'enter_start_chapter': '開始章を入力',
            'enter_valid_int': '有効な正整数を入力してください',
            'env_init_tip': '「実行環境作成」ボタンをクリックしてください！',
            'env_not_initialized': '環境未初期化',
            'error': 'エラー',
            'error_color': 'エラー色',
            'error_color_label': 'エラー色',
            'execute_summary': 'Summary実行',
            'execution_result': '実行結果',
            'exit_confirm_message': '終了してもよろしいですか？',
            'exit_confirm_msg': '終了してもよろしいですか？全スレッドが安全に停止します。',
            'exit_program': 'プログラム終了',
            'export_chapter_format': '章タイトル形式',
            'export_failed': 'エクスポート失敗',
            'export_failed_2': 'エクスポート失敗:\n{0}',
            'export_filename_format': 'ファイル名形式',
            'export_png_btn': 'PNGエクスポート',
            'export_report_btn': 'レポートをエクスポート',
            'export_success': '系統図をエクスポートしました:\n{0}',
            'export_volume_format': '巻タイトル形式',
            'fg_color': 'フォント色',
            'fg_color_label': '前景/文字色',
            'file_suffix_label': 'ファイル接尾辞:',
            'files_unit': 'ファイル',
            'filter_adventure': 'イベント',
            'filter_all': 'すべて',
            'filter_character': 'キャラ',
            'filter_faction': '組織',
            'filter_foreshadowing': '伏線',
            'filter_item': 'アイテム',
            'filter_location': '場所',
            'filter_recent_15': '最近15件',
            'filter_recent_30': '最近30件',
            'filter_recent_50': '最近50件',
            'filter_relationship': '関係',
            'filter_skill': 'スキル',
            'filter_stopwords_label': 'ストップワードフィルタ',
            'filter_time_point': '時間点',
            'focus_mode': '集中モード',
            'folder_exists': 'フォルダ {0} が既に存在します！',
            'folder_status': 'フォルダ状態',
            'follow_theme': 'テーマデフォルトに従う',
            'font_family_label': 'フォント名',
            'font_increment': 'フォントサイズ増分',
            'font_label': 'フォント',
            'font_scaling_label': 'フォント自動スケーリング（オプション）',
            'font_scaling_tooltip': 'ウィンドウサイズに応じてフォントサイズを自動調整します',
            'font_size_label': 'フォントサイズ:',
            'format_config': 'フォーマット設定',
            'format_error_text': '形式エラー',
            'format_help_chapter': '形式：{cn.up.Chapter}=第壹佰伍拾叁章、{cn.low.Chapter}=第一百五十三章、{cn.num.Chapter}=第153章、{en.Chapter}=Chapter153、{jp.Chapter}=第一百五十三章、{name}=接尾辞 | _ は言語形式と{name}の間で自動的に·に変換',
            'format_help_filename': '形式：{num}=数字、{cn.up.Chapter}=第壹佰伍拾叁章、{cn.low.Chapter}=第一百五十三章、{cn.num.Chapter}=第153章、{en.Chapter}=Chapter153、{jp.Chapter}=第一百五十三章、{title}=タイトル名、{types:xxx}=拡張子 | 例：{cn.low.Chapter}{title}{types:markdown} → 1第一章_title.md',
            'format_help_font_label': 'ヘルプ字号',
            'format_help_volume': '形式：{cn.up.Volume}=第壹佰伍拾叁巻、{cn.low.Volume}=第一百五十三巻、{cn.num.Volume}=第153巻、{en.Volume}=Volume153、{jp.Volume}=第一百五十三巻、{name}=巻名、{word_count}=文字数 | _ は言語形式と{name}の間で自動的に·に変換',
            'freq_scan_failed': '頻度スキャン失敗',
            'freq_track_group': '頻度追跡',
            'generate_templates': '2. /all に章テンプレートを生成',
            'generating_chapters': '{0} 章テンプレートを生成中...',
            'glow_size_config': 'グローサイズ設定',
            'glow_tooltip': '有効にするとノードにグロー視覚効果が追加されます',
            'graph_bg_color': '背景色',
            'graph_config': 'グラフ設定',
            'graph_font_size_label': 'ネットワーク図字号',
            'grid_color_label': 'グリッド色',
            'h1_color': 'H1色',
            'h1_font_size': 'H1フォントサイズ',
            'h2_color': 'H2色',
            'h2_font_size': 'H2フォントサイズ',
            'heartbeat_timeout_label': 'ハートビートタイムアウト(秒)',
            'height_scale': '高さ倍率',
            'hint': 'ヒント',
            'inactive_chapters_label': '非アクティブ閾値(章)',
            'init_and_create_tab': '初期化と作成',
            'init_folders_failed': 'フォルダ初期化失敗',
            'init_novel_btn': '小説を初期化',
            'initial_height': '初期高さ',
            'initial_width': '初期幅',
            'initialize_complete': 'ディレクトリの初期化が完了しました！',
            'initialize_directory': 'ディレクトリを初期化',
            'initialize_directory_msg': 'ディレクトリが空か巻フォルダが見つかりません。自動的に初期化しますか？\n\n作成内容：\n  - 1[new_0]/（第一巻）\n  - 10個の空き章\n\n続行しますか？',
            'initialize_failed': 'ディレクトリの初期化に失敗しました',
            'input_bg': '入力框バックグラウンド',
            'input_bg_color': '入力欄背景色',
            'input_error': '入力エラー',
            'key': 'key',
            'keyword_color_label': '色:',
            'keyword_config': 'キーワード設定',
            'keyword_count': 'キーワード数: {0}',
            'keyword_coverage': 'キーワードカバレッジ',
            'keyword_desc_label': '説明:',
            'keyword_list_title': 'キーワードリスト',
            'keyword_manager': 'キーワード管理',
            'keyword_name_label': 'キーワード名:',
            'keyword_page_title': '=== キーワード管理システム ===',
            'keyword_related_label': '関連キーワード（カンマ区切り）:',
            'keyword_tab_title': 'キーワード管理',
            'keyword_type_character': 'キャラクター',
            'keyword_type_custom': 'カスタム',
            'keyword_type_foreshadowing': '伏線',
            'keyword_type_item': 'アイテム',
            'keyword_type_label': 'タイプ:',
            'keyword_type_location': '場所',
            'keyword_type_relationship': '関係',
            'keyword_type_skill': 'スキル',
            'keywords_only_label': 'キーワードのみ',
            'kwlist_color_label': 'キーワード色',
            'kwlist_family_label': 'キーワードフォント',
            'kwlist_font_size_label': 'キーワード字号',
            'kwlist_title_size_label': 'キーワードタイトル字号',
            'language': '言語',
            'language_changed_restart': '言語が変更されました。完全に適用するには再起動してください。',
            'language_config': '言語設定',
            'language_settings': '言語設定',
            'layout_ideal_distance': '理想的なレイアウト距離',
            'layout_ideal_label': '理想的な長さ',
            'legend_position': '凡例位置',
            'legend_style': '凡例スタイル',
            'legend_visible': '凡例を表示',
            'line_height_label': '行間',
            'link_bold': 'リンク太字',
            'link_color': 'リンク色',
            'link_font_size': 'リンクフォントサイズ',
            'link_italic': 'リンク斜体',
            'log_auto_init_done': '作成: 1[new_0]/ (10空)',
            'log_auto_summary_err': '自動Summary失敗: ',
            'log_auto_summary_merging': '新巻処理完了、Summary実行...',
            'log_complete_count': '完了! {0}ファイル作成',
            'log_created_chapter': '作成: ',
            'log_export_failed': 'エクスポート失敗',
            'log_exported_png': 'エクスポート: ',
            'log_failed_chapter': '失敗: ',
            'log_filter': 'ログフィルター',
            'log_font_size': 'ログフォントサイズ',
            'log_isolated_found': '孤立ノード {0} 個発見:',
            'log_layout_reset': 'レイアウトリセット、再計算中',
            'log_layout_saved': 'レイアウト保存完了',
            'log_new_vol_created': '新規巻フォルダ: {0}、監視が処理',
            'log_new_vol_failed': '巻作成失敗: ',
            'log_no_isolated': '孤立ノードなし',
            'log_novel_dir_set': '小説ディレクトリ設定: ',
            'log_p2p_path': 'パス: ',
            'log_path_not_found': '経路なし {0}->{1}',
            'log_rename_item': 'リネーム: {0} -> {1}',
            'log_summary_done': 'Summaryマージ完了',
            'log_wait_monitor': '監視スレッド終了待機...',
            'long_break': '長い休憩',
            'mark_new_volume_failed': '新巻マーク失敗',
            'mark_old_volume_failed': '旧巻マーク失敗',
            'max_nodes': '最大ノード数',
            'max_size_label': '最大サイズ',
            'maximum': '最大:',
            'maximum_label': '最大値',
            'merge_selected_volumes': '選択した巻を結合',
            'merge_volumes_btn': '巻を結合',
            'min_height': '最小高さ',
            'min_occurrences_label': '最小出現回数',
            'min_size_label': '最小サイズ',
            'min_width': '最小幅',
            'min_word_length_label': '最小語長',
            'minimum': '最小:',
            'minimum_label': '最小値',
            'monitor_auto_process': '監視が実行中です。自動的に処理されます。',
            'monitor_check_error': '監視チェック異常',
            'monitor_config': '監視設定',
            'monitor_error': '監視スレッドエラー',
            'monitor_fatal_error': '監視スレッド致命的エラー',
            'monitor_interval': '監視間隔',
            'monitor_management': '監視管理',
            'monitor_started': '監視開始',
            'monitor_stopped': '監視停止',
            'monitor_system': '=== 監視管理システム ===',
            'neural_graph_group': 'ニューラルネットワーク図',
            'new': '新規',
            'new_chapter_detected': '新規章検出',
            'new_chapters_added': '新規章追加',
            'new_folder_detected': '新規フォルダ検出',
            'new_folder_state': '新しいフォルダ状態を発見',
            'new_volume_created': '新規巻を作成しました',
            'new_volume_marked': '新巻マーク',
            'no_data_to_export': 'エクスポートするデータがありません。先に更新してください',
            'no_templates_available': '利用可能なテンプレートはありません',
            'no_vol_folders_warn': '巻フォルダなし',
            'no_volume_folders': '巻フォルダが見つかりません！',
            'node_already_exists': 'ノードは既に存在します',
            'node_brightness_range': 'ノード輝度範囲',
            'node_limit_label': 'ノード上限',
            'node_size_range': 'ノードサイズ範囲',
            'node_visual_effects': 'ノード視覚効果',
            'non_whitespace': '非空白文字',
            'novel_dir': '小説ディレクトリ:',
            'novel_dir_label': '小説ディレクトリ',
            'novel_dir_not_set': '小説ディレクトリを設定',
            'novel_info': '小説情報',
            'ok': 'OK',
            'old_volume_marked': '旧巻マーク',
            'param_config_page': '=== パラメータ設定 ===',
            'parameter_config': 'パラメータ設定',
            'pause': '一時停止',
            'please_init_or_select_novel_dir': '小説ディレクトリを初期化または選択してください',
            'please_select_at_least_one_volume': '少なくとも1つの巻を選択してください',
            'pos_bottom_left': '左下',
            'pos_bottom_right': '右下',
            'pos_top_left': '左上',
            'pos_top_right': '右上',
            'pregenerate_chapters': '予生成章数',
            'prev_volume_not_found': '前の巻が見つかりません',
            'preview_color': 'プレビュー色',
            'preview_font_size': 'プレビューフォントサイズ',
            'preview_text': 'プレビュー: ',
            'process_new_volume_failed': '新巻フォルダ処理失敗',
            'progress': '進捗',
            'prompt': 'プロンプト',
            'quick_operations': 'クイック操作',
            'range_min_max_error': '最小値は最大値より大きくできません！',
            'range_rule_conflict_error': '範囲ルールはしきい値ルールと共存できません！',
            'read_failed': '読み込みに失敗しました',
            'recent_operations': '最近の操作',
            'reference_width': '基準幅',
            'refresh_btn': 'キーワードを更新',
            'refresh_all_btn': 'すべてを更新',
            'reload': '再読み込み',
            'reload_config': '設定を再読み込み',
            'reload_failed': '再読み込みに失敗しました',
            'reset': 'リセット',
            'reset_config_confirm': 'すべての設定をデフォルトにリセットしてもよろしいですか？',
            'reset_config_done': '設定がデフォルトにリセットされました',
            'reset_default_btn': 'デフォルトに戻す',
            'reset_layout_btn': 'レイアウトリセット',
            'restart_to_apply': '言語変更を適用するにはプログラムを再起動してください。',
            'resume': '再開',
            'rule_conflict': 'ルール衝突',
            'rule_type': 'ルールタイプ',
            'rules_help': '接続数しきい値 - ノードの接続数がこの値に達すると、対応するサイズと明るさが適用されます。範囲ルールは接続数区間に作用します。',
            'run_mode': '実行モード',
            'sample_config_created': 'サンプル設定作成: {0}',
            'save_and_apply': '保存して適用',
            'save_and_exit_btn': '保存して終了',
            'save_apply_failed': '保存と適用に失敗しました',
            'save_config': '設定を保存',
            'save_config_failed': '設定の保存に失敗しました',
            'save_directory_label': '保存ディレクトリ:',
            'save_layout_btn': 'レイアウト保存',
            'save_rule': 'ルール保存',
            'save_rule_failed': 'ルールの保存に失敗しました',
            'saving_text': '保存中...',
            'scaling_range': 'スケーリング範囲',
            'scan_failed': '頻度スキャン失敗:\n{0}',
            'scan_in_progress': '頻度スキャン実行中、お待ちください',
            'search_placeholder': 'ノード検索...(Enter)',
            'select': '選択...',
            'select_all_btn': '全選択',
            'select_at_least_one_volume': '少なくとも1つの巻を選択してください',
            'select_directory': 'ディレクトリを選択',
            'select_language': '言語を選択',
            'select_novel_directory': '小説ディレクトリを選択',
            'select_root_node_first': 'ルートノードを選択して系統図を生成してください',
            'select_rule_first': '削除するルールを先に選択してください',
            'select_volumes_label': '結合する巻を選択：',
            'set_novel_dir_first': '小説ディレクトリを先に設定してください',
            'short_break': '短い休憩',
            'show': '表示',
            'size_label': 'サイズ',
            'size_range': 'サイズ範囲',
            'size_sort_tooltip': '接続数の多い順にノードサイズを並べ替えます',
            'skip_break': '休憩をスキップ',
            'skipped_existing': '既存をスキップ',
            'sort_by_connection_brightness': '接続数でノードの明るさをソート',
            'sort_by_connection_size': '接続数でノードサイズをソート',
            'stale_gap_label': '古い呼称検出間隔',
            'stale_ratio_label': '古い呼称検出比率',
            'start': '開始',
            'start_chapter_label': '開始章',
            'start_creation': '作成開始',
            'start_gt_end_error': '開始 > 終了',
            'start_lt_end': '開始章は終了章より大きくできません',
            'start_monitor': '監視開始',
            'start_monitor_process': '監視を開始して新規巻を処理してください。',
            'stats_analysis': '統計と分析',
            'start_must_gt_zero': '開始章は0より大きくなければなりません',
            'start_new_program': '新規プログラム起動',
            'start_program_failed': '新規プログラム起動に失敗しました',
            'start_program_now_question': '新規プログラムを起動しますか？',
            'statistics': '統計',
            'stats_and_rename': '2. 統計してフォルダ名変更',
            'stats_only': '1. 統計のみ（フォルダ名変更なし）',
            'status_running': '状態：実行中',
            'status_stopped': '状態：停止',
            'stop_monitor': '監視停止',
            'structure_preview': '構造プレビュー',
            'success': '成功',
            'summary_execute_failed': 'サマリー実行失敗',
            'summary_merge_tool': '巻と章の結合',
            'summary_triggered': 'Summaryトリガー',
            'tab_config': 'タブ設定',
            'target': '目標',
            'template_saved': 'テンプレートを保存しました',
            'theme_label': 'テーマ',
            'theme_tooltip': 'アプリケーションのビジュアルテーマを選択します',
            'threshold_exists_error': '閾値 {0} は既に存在します。範囲ルールは閾値ルールと共存できません！',
            'threshold_label': 'しきい値',
            'tip_change_language': 'ヒント：言語変更後は「保存して適用」をクリック',
            'title_font_size': 'タイトルフォントサイズ',
            'today': '今日',
            'total_words': '総文字数',
            'trigger_word_count': 'トリガー文字数',
            'ui_color_config': 'UI色設定',
            'ui_size_config': 'UIサイズ設定',
            'user_guide': '使用説明',
            'user_guide_page': '=== 使用説明 ===',
            'view_all_keywords': 'すべてのキーワード',
            'view_by_type': 'タイプで表示',
            'view_card': 'カード表示',
            'view_frequency': '頻度ダッシュボード',
            'view_list': 'リスト表示',
            'view_neural': 'ニューラルネット',
            'volume_details': '各巻詳細',
            'volume_folder_format': '巻フォルダ形式',
            'volume_merge_title': '巻と章の結合',
            'volume_target_words': '巻目標文字数',
            'volume_word_count': '巻字数',
            'waiting_for_write': '書き込み待ち',
            'warn_color_label': '警告色',
            'warning': '警告',
            'word_unit': ' 字',
            'writing_days': '執筆日数',
            'writing_goal_config': '執筆目標設定',
            'writing_stats': '執筆統計',
            'writing_timer': '執筆タイマー',
            'writing_trend': '執筆トレンド',
            '{k}': '{k}',
        },
    }

    def __init__(self):
        self._current_lang = None
        self._translations = {}
        self._available_languages = []
        self._json_translations = {}
        self.load_translations_from_json()

    def load_translations_from_json(self):
        trans_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'translations')
        if not os.path.isdir(trans_dir):
            return
        for fname in os.listdir(trans_dir):
            if fname.endswith('.json'):
                lang = fname.replace('.json', '')
                fpath = os.path.join(trans_dir, fname)
                try:
                    with open(fpath, 'r', encoding='utf-8') as f:
                        data = json.load(f)
                    if lang in data:
                        self._json_translations[lang] = data[lang]
                    logger.info(f"加载翻译文件: {fname}")
                except Exception as e:
                    logger.warning(f"加载翻译文件失败 {fname}: {e}")

    @staticmethod
    def generate_ini_file():
        config_path = ConfigManager.get_config_file_path()
        if os.path.exists(config_path):
            return
        with open(config_path, 'w', encoding='utf-8') as f:
            f.write('[UI]\n')
            f.write('base_font_size = 18\n')
            f.write('base_title_size = 22\n')
            f.write('initial_width = 1100\n')
            f.write('initial_height = 975\n')
            f.write('min_width = 800\n')
            f.write('min_height = 600\n')
            f.write('log_font_size = 16\n')
            f.write('bg_color = #0D0208\n')
            f.write('fg_color = #00FF41\n')
            f.write('border_color = #00FF41\n')
            f.write('accent_color = #00FF41\n')
            f.write('error_color = #FF4444\n')
            f.write('btn_bg_color = #001100\n')
            f.write('btn_hover_color = #003300\n')
            f.write('input_bg_color = #001100\n\n')
            f.write('[Monitor]\n')
            f.write('check_interval = 15\n')
            f.write('max_ahead_chapters = 2\n')
            f.write('min_word_count = 20\n')
            f.write('novel_dir = \n\n')
            f.write('[Adaptive]\n')
            f.write('area_scale_factor = 1.5\n')
            f.write('height_scale_factor = 1.2\n')
            f.write('font_increase = 2\n\n')
            f.write('[Environment]\n')
            f.write('init_chapter_count = 2000\n')
            f.write('init_copy_count = 10\n')
            f.write('pending_delete = 0\n\n')
            f.write('[Language]\n')
            f.write('current = zh_CN\n')
    
    def load_available_languages(self):
        self._available_languages = list(self.DEFAULT_TRANSLATIONS.keys())
        return self._available_languages
    
    def get_current_language(self):
        if self._current_lang is None:
            self._current_lang = ConfigManager.get('Language', 'current', fallback='zh_CN')
        return self._current_lang
    
    def set_current_language(self, lang_code):
        self._current_lang = lang_code
        ConfigManager.set('Language', 'current', lang_code)
        self._translations = {}
    
    def get_available_languages(self):
        if not self._available_languages:
            self.load_available_languages()
        return self._available_languages
    
    def get_translation(self, key):
        current_lang = self.get_current_language()
        if current_lang in self._json_translations:
            if key in self._json_translations[current_lang]:
                return self._json_translations[current_lang][key]
        if current_lang in self.DEFAULT_TRANSLATIONS:
            if key in self.DEFAULT_TRANSLATIONS[current_lang]:
                return self.DEFAULT_TRANSLATIONS[current_lang][key]
        config = ConfigManager.load_config()
        section = f'Language_{current_lang}'
        if config.has_section(section):
            if config.has_option(section, key):
                return config.get(section, key)
        logger.warning(f"翻译缺失: [{current_lang}] {key}")
        return key
    
    def validate_translations(self):
        all_keys = set()
        for lang, trans in self.DEFAULT_TRANSLATIONS.items():
            all_keys.update(trans.keys())
        
        missing = {}
        for lang in self.DEFAULT_TRANSLATIONS:
            lang_missing = []
            for key in all_keys:
                if key not in self.DEFAULT_TRANSLATIONS[lang]:
                    lang_missing.append(key)
            if lang_missing:
                missing[lang] = lang_missing
        
        if missing:
            for lang, keys in missing.items():
                logger.warning(f"语言 {lang} 缺失 {len(keys)} 个翻译: {', '.join(keys[:5])}{'...' if len(keys) > 5 else ''}")






        return missing
    
    def tr(self, key):
        return self.get_translation(key)


language_manager = LanguageManager()

language_manager = LanguageManager()
